/**
 * Test mode, as the agent channel sees it.
 *
 * The API's test mode is chosen by the key (`test_…` prefix, same host, same
 * endpoints), so the MCP server needs no separate deployment and no new tool:
 * a user who pastes a test key into their client gets fixtures through the
 * tools they already have. That part is free.
 *
 * What is not free is the consequence. Every other consumer of a test-mode
 * response is a program that will notice `X-Generect-Mode: test` — or at least
 * a developer reading JSON. An LLM will not. Hand a model twelve fictional
 * prospects with no marker and it will summarise them as twelve prospects, and
 * the person reading that summary has no way to tell. The most likely failure
 * of test mode in an agent is not a wrong number; it is a confident report
 * about people who do not exist.
 *
 * So a test-mode result is annotated where the model actually reads: a field in
 * `structuredContent`, and a sentence at the top of the text block, on every
 * tool, with no way to opt out.
 */

import { parseAuthHeader } from './auth/parse.js';
import { verifyAccessToken, extractApiToken } from './auth/jwt.js';

/** Prefix the API puts on every test key. Live keys are bare hex. */
export const TEST_KEY_PREFIX = 'test_';

export const TEST_MODE_NOTICE =
  'GENERECT TEST MODE. Every person, company, email and phone number in this ' +
  'result is fictional and was generated by the sandbox — nothing was looked ' +
  'up and nothing was charged. Do not present these as real prospects, do not ' +
  'contact them, and do not save them to a CRM. Say plainly that this is test ' +
  'data. Switch to a live API key for real results.';

/** True when this credential is a Generect test key. */
export function isTestCredential(credential: string | null | undefined): boolean {
  if (!credential) return false;
  return credential.trim().replace(/^(bearer|token)\s+/i, '').startsWith(TEST_KEY_PREFIX);
}

/**
 * Whether the request behind this tool call is using a test key.
 *
 * Reads the credential rather than the response header on purpose: it is
 * decided before the call, so the annotation is attached even when the tool
 * returns an error, and it works identically for a raw API key and for an
 * OAuth access token that carries the key inside it. Never throws — a mode we
 * cannot determine is reported as live, which is the honest default: the
 * annotation makes a claim, and a wrong claim of "this is fake" is worse than
 * no claim at all.
 */
export async function isTestRequest(extra: any): Promise<boolean> {
  try {
    const header = extra?.requestInfo?.headers?.authorization as string | undefined;
    const parsed = parseAuthHeader(header);
    if (!parsed) return false;
    if (parsed.kind === 'token') return isTestCredential(parsed.apiKey);
    const payload = await verifyAccessToken(parsed.jwt);
    return payload ? isTestCredential(extractApiToken(payload)) : false;
  } catch {
    return false;
  }
}

/** Adds the test-mode marker to an MCP tool result, in both channels. */
export function annotate(result: any): any {
  if (!result || typeof result !== 'object') return result;
  const structured = result.structuredContent;
  const content = Array.isArray(result.content) ? result.content : [];
  return {
    ...result,
    ...(structured && typeof structured === 'object'
      ? { structuredContent: { test_mode: true, test_mode_notice: TEST_MODE_NOTICE, ...structured } }
      : {}),
    content: [{ type: 'text' as const, text: TEST_MODE_NOTICE }, ...content],
  };
}
