// GENERATED by scripts/gen-vocabulary.mjs — do not edit by hand.
// Source of truth: generect/api_parser
//   linkedin_parser/utils/categories_relationship.json   (industries)
//   linkedin_parser/utils/urlcreator/data_dicts.py       (seniorities, functions, follower ranges)
//   linkedin/utils/lead_list_url.py  -> type_dict        (company types)
// Regenerate with: node scripts/gen-vocabulary.mjs <api_parser checkout>

export interface IndustryNode {
  name: string;
  parent: string | null;
}

export const INDUSTRIES: readonly IndustryNode[] = [
  {
    name: 'Abrasives and Nonmetallic Minerals Manufacturing',
    parent: 'Glass, Ceramics and Concrete Manufacturing',
  },
  {
    name: 'Accessible Architecture and Design',
    parent: 'Architecture and Planning',
  },
  {
    name: 'Accessible Hardware Manufacturing',
    parent: 'Computer Hardware Manufacturing',
  },
  {
    name: 'Accommodation and Food Services',
    parent: null,
  },
  {
    name: 'Accounting',
    parent: 'Professional Services',
  },
  {
    name: 'Administration of Justice',
    parent: 'Government Administration',
  },
  {
    name: 'Administrative and Support Services',
    parent: null,
  },
  {
    name: 'Advertising Services',
    parent: 'Professional Services',
  },
  {
    name: 'Agricultural Chemical Manufacturing',
    parent: 'Chemical Manufacturing',
  },
  {
    name: 'Agriculture, Construction, Mining Machinery Manufacturing',
    parent: 'Machinery Manufacturing',
  },
  {
    name: 'Air, Water, and Waste Program Management',
    parent: 'Environmental Quality Programs',
  },
  {
    name: 'Airlines and Aviation',
    parent: 'Transportation, Logistics, Supply Chain and Storage',
  },
  {
    name: 'Alternative Dispute Resolution',
    parent: 'Legal Services',
  },
  {
    name: 'Alternative Fuel Vehicle Manufacturing',
    parent: 'Motor Vehicle Manufacturing',
  },
  {
    name: 'Alternative Medicine',
    parent: 'Medical Practices',
  },
  {
    name: 'Ambulance Services',
    parent: 'Medical Practices',
  },
  {
    name: 'Amusement Parks and Arcades',
    parent: 'Recreational Facilities',
  },
  {
    name: 'Animal Feed Manufacturing',
    parent: 'Food and Beverage Manufacturing',
  },
  {
    name: 'Animation and Post-production',
    parent: 'Movies, Videos and Sound',
  },
  {
    name: 'Apparel Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Appliances, Electrical, and Electronics Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Architectural and Structural Metal Manufacturing',
    parent: 'Fabricated Metal Products',
  },
  {
    name: 'Architecture and Planning',
    parent: 'Professional Services',
  },
  {
    name: 'Armed Forces',
    parent: 'Military and International Affairs',
  },
  {
    name: 'Artificial Rubber and Synthetic Fiber Manufacturing',
    parent: 'Chemical Manufacturing',
  },
  {
    name: 'Artists and Writers',
    parent: 'Entertainment Providers',
  },
  {
    name: 'Audio and Video Equipment Manufacturing',
    parent: 'Computers and Electronics Manufacturing',
  },
  {
    name: 'Automation Machinery Manufacturing',
    parent: 'Machinery Manufacturing',
  },
  {
    name: 'Aviation and Aerospace Component Manufacturing',
    parent: 'Transportation Equipment Manufacturing',
  },
  {
    name: 'Baked Goods Manufacturing',
    parent: 'Food and Beverage Manufacturing',
  },
  {
    name: 'Banking',
    parent: 'Credit Intermediation',
  },
  {
    name: 'Bars, Taverns, and Nightclubs',
    parent: 'Food and Beverage Services',
  },
  {
    name: 'Bed-and-Breakfasts, Hostels, Homestays',
    parent: 'Hospitality',
  },
  {
    name: 'Beverage Manufacturing',
    parent: 'Food and Beverage Manufacturing',
  },
  {
    name: 'Biomass Electric Power Generation',
    parent: 'Renewable Energy Power Generation',
  },
  {
    name: 'Biotechnology Research',
    parent: 'Research Services',
  },
  {
    name: 'Blockchain Services',
    parent: 'Data Infrastructure and Analytics',
  },
  {
    name: 'Blogs',
    parent: 'Internet Publishing',
  },
  {
    name: 'Boilers, Tanks, and Shipping Container Manufacturing',
    parent: 'Fabricated Metal Products',
  },
  {
    name: 'Book and Periodical Publishing',
    parent: 'Media and Telecommunications',
  },
  {
    name: 'Book Publishing',
    parent: 'Book and Periodical Publishing',
  },
  {
    name: 'Breweries',
    parent: 'Food and Beverage Manufacturing',
  },
  {
    name: 'Broadcast Media Production and Distribution',
    parent: 'Media and Telecommunications',
  },
  {
    name: 'Building Construction',
    parent: 'Construction',
  },
  {
    name: 'Building Equipment Contractors',
    parent: 'Specialty Trade Contractors',
  },
  {
    name: 'Building Finishing Contractors',
    parent: 'Specialty Trade Contractors',
  },
  {
    name: 'Building Structure and Exterior Contractors',
    parent: 'Specialty Trade Contractors',
  },
  {
    name: 'Business Consulting and Services',
    parent: 'Professional Services',
  },
  {
    name: 'Business Content',
    parent: 'Internet Publishing',
  },
  {
    name: 'Business Intelligence Platforms',
    parent: 'Data Infrastructure and Analytics',
  },
  {
    name: 'Cable and Satellite Programming',
    parent: 'Broadcast Media Production and Distribution',
  },
  {
    name: 'Capital Markets',
    parent: 'Financial Services',
  },
  {
    name: 'Caterers',
    parent: 'Food and Beverage Services',
  },
  {
    name: 'Chemical Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Chemical Raw Materials Manufacturing',
    parent: 'Chemical Manufacturing',
  },
  {
    name: 'Child Day Care Services',
    parent: 'Individual and Family Services',
  },
  {
    name: 'Chiropractors',
    parent: 'Medical Practices',
  },
  {
    name: 'Circuses and Magic Shows',
    parent: 'Performing Arts and Spectator Sports',
  },
  {
    name: 'Civic and Social Organizations',
    parent: 'Consumer Services',
  },
  {
    name: 'Civil Engineering',
    parent: 'Construction',
  },
  {
    name: 'Claims Adjusting, Actuarial Services',
    parent: 'Insurance',
  },
  {
    name: 'Clay and Refractory Products Manufacturing',
    parent: 'Glass, Ceramics and Concrete Manufacturing',
  },
  {
    name: 'Climate Data and Analytics',
    parent: 'Data Infrastructure and Analytics',
  },
  {
    name: 'Climate Technology Product Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Coal Mining',
    parent: 'Mining',
  },
  {
    name: 'Collection Agencies',
    parent: 'Administrative and Support Services',
  },
  {
    name: 'Commercial and Industrial Equipment Rental',
    parent: 'Equipment Rental Services',
  },
  {
    name: 'Commercial and Industrial Machinery Maintenance',
    parent: 'Repair and Maintenance',
  },
  {
    name: 'Commercial and Service Industry Machinery Manufacturing',
    parent: 'Machinery Manufacturing',
  },
  {
    name: 'Communications Equipment Manufacturing',
    parent: 'Computers and Electronics Manufacturing',
  },
  {
    name: 'Community Development and Urban Planning',
    parent: 'Housing and Community Development',
  },
  {
    name: 'Community Services',
    parent: 'Hospitals and Health Care',
  },
  {
    name: 'Computer and Network Security',
    parent: 'IT Services and IT Consulting',
  },
  {
    name: 'Computer Games',
    parent: 'Software Development',
  },
  {
    name: 'Computer Hardware Manufacturing',
    parent: 'Computers and Electronics Manufacturing',
  },
  {
    name: 'Computer Networking Products',
    parent: 'Software Development',
  },
  {
    name: 'Computers and Electronics Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Conservation Programs',
    parent: 'Environmental Quality Programs',
  },
  {
    name: 'Construction',
    parent: null,
  },
  {
    name: 'Construction Hardware Manufacturing',
    parent: 'Fabricated Metal Products',
  },
  {
    name: 'Consumer Goods Rental',
    parent: 'Equipment Rental Services',
  },
  {
    name: 'Consumer Services',
    parent: null,
  },
  {
    name: 'Correctional Institutions',
    parent: 'Administration of Justice',
  },
  {
    name: 'Cosmetology and Barber Schools',
    parent: 'Technical and Vocational Training',
  },
  {
    name: 'Courts of Law',
    parent: 'Administration of Justice',
  },
  {
    name: 'Credit Intermediation',
    parent: 'Financial Services',
  },
  {
    name: 'Cutlery and Handtool Manufacturing',
    parent: 'Fabricated Metal Products',
  },
  {
    name: 'Dairy Product Manufacturing',
    parent: 'Food and Beverage Manufacturing',
  },
  {
    name: 'Dance Companies',
    parent: 'Performing Arts and Spectator Sports',
  },
  {
    name: 'Data Infrastructure and Analytics',
    parent: 'Technology, Information and Internet',
  },
  {
    name: 'Data Security Software Products',
    parent: 'Software Development',
  },
  {
    name: 'Defense and Space Manufacturing',
    parent: 'Transportation Equipment Manufacturing',
  },
  {
    name: 'Dentists',
    parent: 'Medical Practices',
  },
  {
    name: 'Design Services',
    parent: 'Professional Services',
  },
  {
    name: 'Desktop Computing Software Products',
    parent: 'Software Development',
  },
  {
    name: 'Digital Accessibility Services',
    parent: 'IT Services and IT Consulting',
  },
  {
    name: 'Distilleries',
    parent: 'Food and Beverage Manufacturing',
  },
  {
    name: 'E-Learning Providers',
    parent: 'Education',
  },
  {
    name: 'Economic Programs',
    parent: 'Government Administration',
  },
  {
    name: 'Education',
    parent: null,
  },
  {
    name: 'Education Administration Programs',
    parent: 'Health and Human Services',
  },
  {
    name: 'Electric Lighting Equipment Manufacturing',
    parent: 'Appliances, Electrical, and Electronics Manufacturing',
  },
  {
    name: 'Electric Power Generation',
    parent: 'Utilities',
  },
  {
    name: 'Electric Power Transmission, Control, and Distribution',
    parent: 'Utilities',
  },
  {
    name: 'Electrical Equipment Manufacturing',
    parent: 'Appliances, Electrical, and Electronics Manufacturing',
  },
  {
    name: 'Electronic and Precision Equipment Maintenance',
    parent: 'Repair and Maintenance',
  },
  {
    name: 'Embedded Software Products',
    parent: 'Software Development',
  },
  {
    name: 'Emergency and Relief Services',
    parent: 'Individual and Family Services',
  },
  {
    name: 'Engineering Services',
    parent: 'Professional Services',
  },
  {
    name: 'Engines and Power Transmission Equipment Manufacturing',
    parent: 'Machinery Manufacturing',
  },
  {
    name: 'Entertainment Providers',
    parent: null,
  },
  {
    name: 'Environmental Quality Programs',
    parent: 'Government Administration',
  },
  {
    name: 'Environmental Services',
    parent: 'Business Consulting and Services',
  },
  {
    name: 'Equipment Rental Services',
    parent: 'Real Estate and Equipment Rental Services',
  },
  {
    name: 'Events Services',
    parent: 'Administrative and Support Services',
  },
  {
    name: 'Executive Offices',
    parent: 'Public Policy Offices',
  },
  {
    name: 'Executive Search Services',
    parent: 'Staffing and Recruiting',
  },
  {
    name: 'Fabricated Metal Products',
    parent: 'Manufacturing',
  },
  {
    name: 'Facilities Services',
    parent: 'Administrative and Support Services',
  },
  {
    name: 'Family Planning Centers',
    parent: 'Medical Practices',
  },
  {
    name: 'Farming',
    parent: 'Farming, Ranching, Forestry',
  },
  {
    name: 'Farming, Ranching, Forestry',
    parent: null,
  },
  {
    name: 'Fashion Accessories Manufacturing',
    parent: 'Apparel Manufacturing',
  },
  {
    name: 'Financial Services',
    parent: null,
  },
  {
    name: 'Fine Arts Schools',
    parent: 'Technical and Vocational Training',
  },
  {
    name: 'Fire Protection',
    parent: 'Administration of Justice',
  },
  {
    name: 'Fisheries',
    parent: 'Ranching and Fisheries',
  },
  {
    name: 'Flight Training',
    parent: 'Technical and Vocational Training',
  },
  {
    name: 'Food and Beverage Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Food and Beverage Retail',
    parent: 'Retail',
  },
  {
    name: 'Food and Beverage Services',
    parent: 'Accommodation and Food Services',
  },
  {
    name: 'Footwear and Leather Goods Repair',
    parent: 'Repair and Maintenance',
  },
  {
    name: 'Footwear Manufacturing',
    parent: 'Leather Product Manufacturing',
  },
  {
    name: 'Forestry and Logging',
    parent: 'Farming, Ranching, Forestry',
  },
  {
    name: 'Fossil Fuel Electric Power Generation',
    parent: 'Electric Power Generation',
  },
  {
    name: 'Freight and Package Transportation',
    parent: 'Transportation, Logistics, Supply Chain and Storage',
  },
  {
    name: 'Fruit and Vegetable Preserves Manufacturing',
    parent: 'Food and Beverage Manufacturing',
  },
  {
    name: 'Fuel Cell Manufacturing',
    parent: 'Electrical Equipment Manufacturing',
  },
  {
    name: 'Fundraising',
    parent: 'Administrative and Support Services',
  },
  {
    name: 'Funds and Trusts',
    parent: 'Financial Services',
  },
  {
    name: 'Furniture and Home Furnishings Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Gambling Facilities and Casinos',
    parent: 'Recreational Facilities',
  },
  {
    name: 'Geothermal Electric Power Generation',
    parent: 'Renewable Energy Power Generation',
  },
  {
    name: 'Glass Product Manufacturing',
    parent: 'Glass, Ceramics and Concrete Manufacturing',
  },
  {
    name: 'Glass, Ceramics and Concrete Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Golf Courses and Country Clubs',
    parent: 'Recreational Facilities',
  },
  {
    name: 'Government Administration',
    parent: null,
  },
  {
    name: 'Government Relations Services',
    parent: 'Advertising Services',
  },
  {
    name: 'Graphic Design',
    parent: 'Design Services',
  },
  {
    name: 'Ground Passenger Transportation',
    parent: 'Transportation, Logistics, Supply Chain and Storage',
  },
  {
    name: 'Health and Human Services',
    parent: 'Government Administration',
  },
  {
    name: 'Higher Education',
    parent: 'Education',
  },
  {
    name: 'Highway, Street, and Bridge Construction',
    parent: 'Civil Engineering',
  },
  {
    name: 'Historical Sites',
    parent: 'Museums, Historical Sites, and Zoos',
  },
  {
    name: 'Holding Companies',
    parent: null,
  },
  {
    name: 'Home Health Care Services',
    parent: 'Medical Practices',
  },
  {
    name: 'Horticulture',
    parent: 'Farming',
  },
  {
    name: 'Hospitality',
    parent: 'Accommodation and Food Services',
  },
  {
    name: 'Hospitals',
    parent: 'Hospitals and Health Care',
  },
  {
    name: 'Hospitals and Health Care',
    parent: null,
  },
  {
    name: 'Hotels and Motels',
    parent: 'Hospitality',
  },
  {
    name: 'Household and Institutional Furniture Manufacturing',
    parent: 'Furniture and Home Furnishings Manufacturing',
  },
  {
    name: 'Household Appliance Manufacturing',
    parent: 'Appliances, Electrical, and Electronics Manufacturing',
  },
  {
    name: 'Household Services',
    parent: 'Consumer Services',
  },
  {
    name: 'Housing and Community Development',
    parent: 'Government Administration',
  },
  {
    name: 'Housing Programs',
    parent: 'Housing and Community Development',
  },
  {
    name: 'Human Resources Services',
    parent: 'Business Consulting and Services',
  },
  {
    name: 'HVAC and Refrigeration Equipment Manufacturing',
    parent: 'Machinery Manufacturing',
  },
  {
    name: 'Hydroelectric Power Generation',
    parent: 'Renewable Energy Power Generation',
  },
  {
    name: 'Individual and Family Services',
    parent: 'Hospitals and Health Care',
  },
  {
    name: 'Industrial Machinery Manufacturing',
    parent: 'Machinery Manufacturing',
  },
  {
    name: 'Industry Associations',
    parent: 'Civic and Social Organizations',
  },
  {
    name: 'Information Services',
    parent: 'Technology, Information and Internet',
  },
  {
    name: 'Insurance',
    parent: 'Financial Services',
  },
  {
    name: 'Insurance Agencies and Brokerages',
    parent: 'Insurance',
  },
  {
    name: 'Insurance and Employee Benefit Funds',
    parent: 'Funds and Trusts',
  },
  {
    name: 'Insurance Carriers',
    parent: 'Insurance',
  },
  {
    name: 'Interior Design',
    parent: 'Design Services',
  },
  {
    name: 'International Affairs',
    parent: 'Military and International Affairs',
  },
  {
    name: 'International Trade and Development',
    parent: 'Credit Intermediation',
  },
  {
    name: 'Internet Marketplace Platforms',
    parent: 'Technology, Information and Internet',
  },
  {
    name: 'Internet News',
    parent: 'Online Audio and Video Media',
  },
  {
    name: 'Internet Publishing',
    parent: 'Information Services',
  },
  {
    name: 'Interurban and Rural Bus Services',
    parent: 'Ground Passenger Transportation',
  },
  {
    name: 'Investment Advice',
    parent: 'Capital Markets',
  },
  {
    name: 'Investment Banking',
    parent: 'Capital Markets',
  },
  {
    name: 'Investment Management',
    parent: 'Capital Markets',
  },
  {
    name: 'IT Services and IT Consulting',
    parent: 'Professional Services',
  },
  {
    name: 'IT System Custom Software Development',
    parent: 'IT Services and IT Consulting',
  },
  {
    name: 'IT System Data Services',
    parent: 'IT Services and IT Consulting',
  },
  {
    name: 'IT System Design Services',
    parent: 'IT Services and IT Consulting',
  },
  {
    name: 'IT System Installation and Disposal',
    parent: 'IT Services and IT Consulting',
  },
  {
    name: 'IT System Operations and Maintenance',
    parent: 'IT Services and IT Consulting',
  },
  {
    name: 'IT System Testing and Evaluation',
    parent: 'IT Services and IT Consulting',
  },
  {
    name: 'IT System Training and Support',
    parent: 'IT Services and IT Consulting',
  },
  {
    name: 'Janitorial Services',
    parent: 'Facilities Services',
  },
  {
    name: 'Landscaping Services',
    parent: 'Facilities Services',
  },
  {
    name: 'Language Schools',
    parent: 'Technical and Vocational Training',
  },
  {
    name: 'Laundry and Drycleaning Services',
    parent: 'Personal and Laundry Services',
  },
  {
    name: 'Law Enforcement',
    parent: 'Administration of Justice',
  },
  {
    name: 'Law Practice',
    parent: 'Legal Services',
  },
  {
    name: 'Leasing Non-residential Real Estate',
    parent: 'Real Estate',
  },
  {
    name: 'Leasing Residential Real Estate',
    parent: 'Real Estate',
  },
  {
    name: 'Leather Product Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Legal Services',
    parent: 'Professional Services',
  },
  {
    name: 'Legislative Offices',
    parent: 'Public Policy Offices',
  },
  {
    name: 'Libraries',
    parent: 'Information Services',
  },
  {
    name: 'Lime and Gypsum Products Manufacturing',
    parent: 'Glass, Ceramics and Concrete Manufacturing',
  },
  {
    name: 'Loan Brokers',
    parent: 'Credit Intermediation',
  },
  {
    name: 'Machinery Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Magnetic and Optical Media Manufacturing',
    parent: 'Computers and Electronics Manufacturing',
  },
  {
    name: 'Manufacturing',
    parent: null,
  },
  {
    name: 'Maritime Transportation',
    parent: 'Transportation, Logistics, Supply Chain and Storage',
  },
  {
    name: 'Market Research',
    parent: 'Advertising Services',
  },
  {
    name: 'Marketing Services',
    parent: 'Business Consulting and Services',
  },
  {
    name: 'Mattress and Blinds Manufacturing',
    parent: 'Furniture and Home Furnishings Manufacturing',
  },
  {
    name: 'Measuring and Control Instrument Manufacturing',
    parent: 'Computers and Electronics Manufacturing',
  },
  {
    name: 'Meat Products Manufacturing',
    parent: 'Food and Beverage Manufacturing',
  },
  {
    name: 'Media and Telecommunications',
    parent: 'Technology, Information and Media',
  },
  {
    name: 'Media Production',
    parent: 'Movies, Videos and Sound',
  },
  {
    name: 'Medical and Diagnostic Laboratories',
    parent: 'Medical Practices',
  },
  {
    name: 'Medical Equipment Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Medical Practices',
    parent: 'Hospitals and Health Care',
  },
  {
    name: 'Mental Health Care',
    parent: 'Medical Practices',
  },
  {
    name: 'Metal Ore Mining',
    parent: 'Mining',
  },
  {
    name: 'Metal Treatments',
    parent: 'Fabricated Metal Products',
  },
  {
    name: 'Metal Valve, Ball, and Roller Manufacturing',
    parent: 'Fabricated Metal Products',
  },
  {
    name: 'Metalworking Machinery Manufacturing',
    parent: 'Machinery Manufacturing',
  },
  {
    name: 'Military and International Affairs',
    parent: 'Government Administration',
  },
  {
    name: 'Mining',
    parent: 'Oil, Gas, and Mining',
  },
  {
    name: 'Mobile Computing Software Products',
    parent: 'Software Development',
  },
  {
    name: 'Mobile Food Services',
    parent: 'Food and Beverage Services',
  },
  {
    name: 'Mobile Gaming Apps',
    parent: 'Computer Games',
  },
  {
    name: 'Motor Vehicle Manufacturing',
    parent: 'Transportation Equipment Manufacturing',
  },
  {
    name: 'Motor Vehicle Parts Manufacturing',
    parent: 'Transportation Equipment Manufacturing',
  },
  {
    name: 'Movies and Sound Recording',
    parent: 'Movies, Videos and Sound',
  },
  {
    name: 'Movies, Videos and Sound',
    parent: 'Media and Telecommunications',
  },
  {
    name: 'Museums',
    parent: 'Museums, Historical Sites, and Zoos',
  },
  {
    name: 'Museums, Historical Sites, and Zoos',
    parent: 'Entertainment Providers',
  },
  {
    name: 'Musicians',
    parent: 'Entertainment Providers',
  },
  {
    name: 'Nanotechnology Research',
    parent: 'Research Services',
  },
  {
    name: 'Natural Gas Distribution',
    parent: 'Utilities',
  },
  {
    name: 'Natural Gas Extraction',
    parent: 'Oil and Gas',
  },
  {
    name: 'Newspaper Publishing',
    parent: 'Book and Periodical Publishing',
  },
  {
    name: 'Non-profit Organizations',
    parent: 'Consumer Services',
  },
  {
    name: 'Nonmetallic Mineral Mining',
    parent: 'Mining',
  },
  {
    name: 'Nonresidential Building Construction',
    parent: 'Building Construction',
  },
  {
    name: 'Nuclear Electric Power Generation',
    parent: 'Electric Power Generation',
  },
  {
    name: 'Nursing Homes and Residential Care Facilities',
    parent: 'Hospitals and Health Care',
  },
  {
    name: 'Office Administration',
    parent: 'Administrative and Support Services',
  },
  {
    name: 'Office Furniture and Fixtures Manufacturing',
    parent: 'Furniture and Home Furnishings Manufacturing',
  },
  {
    name: 'Oil and Coal Product Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Oil and Gas',
    parent: 'Oil, Gas, and Mining',
  },
  {
    name: 'Oil Extraction',
    parent: 'Oil and Gas',
  },
  {
    name: 'Oil, Gas, and Mining',
    parent: null,
  },
  {
    name: 'Online and Mail Order Retail',
    parent: 'Retail',
  },
  {
    name: 'Online Audio and Video Media',
    parent: 'Internet Publishing',
  },
  {
    name: 'Operations Consulting',
    parent: 'Business Consulting and Services',
  },
  {
    name: 'Optometrists',
    parent: 'Medical Practices',
  },
  {
    name: 'Outpatient Care Centers',
    parent: 'Medical Practices',
  },
  {
    name: 'Outsourcing and Offshoring Consulting',
    parent: 'Business Consulting and Services',
  },
  {
    name: 'Packaging and Containers Manufacturing',
    parent: 'Plastics and Rubber Product Manufacturing',
  },
  {
    name: 'Paint, Coating, and Adhesive Manufacturing',
    parent: 'Chemical Manufacturing',
  },
  {
    name: 'Paper and Forest Product Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Pension Funds',
    parent: 'Funds and Trusts',
  },
  {
    name: 'Performing Arts',
    parent: 'Performing Arts and Spectator Sports',
  },
  {
    name: 'Performing Arts and Spectator Sports',
    parent: 'Entertainment Providers',
  },
  {
    name: 'Periodical Publishing',
    parent: 'Book and Periodical Publishing',
  },
  {
    name: 'Personal and Laundry Services',
    parent: 'Consumer Services',
  },
  {
    name: 'Personal Care Product Manufacturing',
    parent: 'Chemical Manufacturing',
  },
  {
    name: 'Personal Care Services',
    parent: 'Personal and Laundry Services',
  },
  {
    name: 'Pet Services',
    parent: 'Personal and Laundry Services',
  },
  {
    name: 'Pharmaceutical Manufacturing',
    parent: 'Chemical Manufacturing',
  },
  {
    name: 'Philanthropic Fundraising Services',
    parent: 'Consumer Services',
  },
  {
    name: 'Photography',
    parent: 'Professional Services',
  },
  {
    name: 'Physical, Occupational and Speech Therapists',
    parent: 'Medical Practices',
  },
  {
    name: 'Physicians',
    parent: 'Medical Practices',
  },
  {
    name: 'Pipeline Transportation',
    parent: 'Transportation, Logistics, Supply Chain and Storage',
  },
  {
    name: 'Plastics and Rubber Product Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Plastics Manufacturing',
    parent: 'Plastics and Rubber Product Manufacturing',
  },
  {
    name: 'Political Organizations',
    parent: 'Civic and Social Organizations',
  },
  {
    name: 'Postal Services',
    parent: 'Transportation, Logistics, Supply Chain and Storage',
  },
  {
    name: 'Primary and Secondary Education',
    parent: 'Education',
  },
  {
    name: 'Primary Metal Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Printing Services',
    parent: 'Manufacturing',
  },
  {
    name: 'Professional Organizations',
    parent: 'Civic and Social Organizations',
  },
  {
    name: 'Professional Services',
    parent: null,
  },
  {
    name: 'Professional Training and Coaching',
    parent: 'Education',
  },
  {
    name: 'Public Assistance Programs',
    parent: 'Health and Human Services',
  },
  {
    name: 'Public Health',
    parent: 'Health and Human Services',
  },
  {
    name: 'Public Policy Offices',
    parent: 'Government Administration',
  },
  {
    name: 'Public Relations and Communications Services',
    parent: 'Advertising Services',
  },
  {
    name: 'Public Safety',
    parent: 'Administration of Justice',
  },
  {
    name: 'Racetracks',
    parent: 'Spectator Sports',
  },
  {
    name: 'Radio and Television Broadcasting',
    parent: 'Broadcast Media Production and Distribution',
  },
  {
    name: 'Rail Transportation',
    parent: 'Transportation, Logistics, Supply Chain and Storage',
  },
  {
    name: 'Railroad Equipment Manufacturing',
    parent: 'Transportation Equipment Manufacturing',
  },
  {
    name: 'Ranching',
    parent: 'Ranching and Fisheries',
  },
  {
    name: 'Ranching and Fisheries',
    parent: 'Farming, Ranching, Forestry',
  },
  {
    name: 'Real Estate',
    parent: 'Real Estate and Equipment Rental Services',
  },
  {
    name: 'Real Estate Agents and Brokers',
    parent: 'Real Estate',
  },
  {
    name: 'Real Estate and Equipment Rental Services',
    parent: null,
  },
  {
    name: 'Recreational Facilities',
    parent: 'Entertainment Providers',
  },
  {
    name: 'Regenerative Design',
    parent: 'Design Services',
  },
  {
    name: 'Religious Institutions',
    parent: 'Consumer Services',
  },
  {
    name: 'Renewable Energy Equipment Manufacturing',
    parent: 'Engines and Power Transmission Equipment Manufacturing',
  },
  {
    name: 'Renewable Energy Power Generation',
    parent: 'Electric Power Generation',
  },
  {
    name: 'Renewable Energy Semiconductor Manufacturing',
    parent: 'Semiconductor Manufacturing',
  },
  {
    name: 'Repair and Maintenance',
    parent: 'Consumer Services',
  },
  {
    name: 'Research Services',
    parent: 'Professional Services',
  },
  {
    name: 'Residential Building Construction',
    parent: 'Building Construction',
  },
  {
    name: 'Restaurants',
    parent: 'Food and Beverage Services',
  },
  {
    name: 'Retail',
    parent: null,
  },
  {
    name: 'Retail Apparel and Fashion',
    parent: 'Retail',
  },
  {
    name: 'Retail Appliances, Electrical, and Electronic Equipment',
    parent: 'Retail',
  },
  {
    name: 'Retail Art Dealers',
    parent: 'Retail',
  },
  {
    name: 'Retail Art Supplies',
    parent: 'Retail',
  },
  {
    name: 'Retail Books and Printed News',
    parent: 'Retail',
  },
  {
    name: 'Retail Building Materials and Garden Equipment',
    parent: 'Retail',
  },
  {
    name: 'Retail Florists',
    parent: 'Retail',
  },
  {
    name: 'Retail Furniture and Home Furnishings',
    parent: 'Retail',
  },
  {
    name: 'Retail Gasoline',
    parent: 'Retail',
  },
  {
    name: 'Retail Groceries',
    parent: 'Food and Beverage Retail',
  },
  {
    name: 'Retail Health and Personal Care Products',
    parent: 'Retail',
  },
  {
    name: 'Retail Luxury Goods and Jewelry',
    parent: 'Retail',
  },
  {
    name: 'Retail Motor Vehicles',
    parent: 'Retail',
  },
  {
    name: 'Retail Musical Instruments',
    parent: 'Retail',
  },
  {
    name: 'Retail Office Equipment',
    parent: 'Retail',
  },
  {
    name: 'Retail Office Supplies and Gifts',
    parent: 'Retail',
  },
  {
    name: 'Retail Pharmacies',
    parent: 'Retail Health and Personal Care Products',
  },
  {
    name: 'Retail Recyclable Materials & Used Merchandise',
    parent: 'Retail',
  },
  {
    name: 'Reupholstery and Furniture Repair',
    parent: 'Repair and Maintenance',
  },
  {
    name: 'Robot Manufacturing',
    parent: 'Automation Machinery Manufacturing',
  },
  {
    name: 'Robotics Engineering',
    parent: 'Engineering Services',
  },
  {
    name: 'Rubber Products Manufacturing',
    parent: 'Plastics and Rubber Product Manufacturing',
  },
  {
    name: 'Satellite Telecommunications',
    parent: 'Telecommunications',
  },
  {
    name: 'Savings Institutions',
    parent: 'Credit Intermediation',
  },
  {
    name: 'School and Employee Bus Services',
    parent: 'Ground Passenger Transportation',
  },
  {
    name: 'Seafood Product Manufacturing',
    parent: 'Food and Beverage Manufacturing',
  },
  {
    name: 'Secretarial Schools',
    parent: 'Technical and Vocational Training',
  },
  {
    name: 'Securities and Commodity Exchanges',
    parent: 'Capital Markets',
  },
  {
    name: 'Security and Investigations',
    parent: 'Administrative and Support Services',
  },
  {
    name: 'Security Guards and Patrol Services',
    parent: 'Security and Investigations',
  },
  {
    name: 'Security Systems Services',
    parent: 'Security and Investigations',
  },
  {
    name: 'Semiconductor Manufacturing',
    parent: 'Computers and Electronics Manufacturing',
  },
  {
    name: 'Services for Renewable Energy',
    parent: 'Professional Services',
  },
  {
    name: 'Services for the Elderly and Disabled',
    parent: 'Community Services',
  },
  {
    name: 'Sheet Music Publishing',
    parent: 'Movies, Videos and Sound',
  },
  {
    name: 'Shipbuilding',
    parent: 'Transportation Equipment Manufacturing',
  },
  {
    name: 'Shuttles and Special Needs Transportation Services',
    parent: 'Ground Passenger Transportation',
  },
  {
    name: 'Sightseeing Transportation',
    parent: 'Ground Passenger Transportation',
  },
  {
    name: 'Skiing Facilities',
    parent: 'Recreational Facilities',
  },
  {
    name: 'Smart Meter Manufacturing',
    parent: 'Measuring and Control Instrument Manufacturing',
  },
  {
    name: 'Soap and Cleaning Product Manufacturing',
    parent: 'Chemical Manufacturing',
  },
  {
    name: 'Social Networking Platforms',
    parent: 'Technology, Information and Internet',
  },
  {
    name: 'Software Development',
    parent: 'Technology, Information and Internet',
  },
  {
    name: 'Solar Electric Power Generation',
    parent: 'Renewable Energy Power Generation',
  },
  {
    name: 'Sound Recording',
    parent: 'Movies and Sound Recording',
  },
  {
    name: 'Space Research and Technology',
    parent: 'Government Administration',
  },
  {
    name: 'Specialty Trade Contractors',
    parent: 'Construction',
  },
  {
    name: 'Spectator Sports',
    parent: 'Performing Arts and Spectator Sports',
  },
  {
    name: 'Sporting Goods Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Sports and Recreation Instruction',
    parent: 'Technical and Vocational Training',
  },
  {
    name: 'Sports Teams and Clubs',
    parent: 'Spectator Sports',
  },
  {
    name: 'Spring and Wire Product Manufacturing',
    parent: 'Fabricated Metal Products',
  },
  {
    name: 'Staffing and Recruiting',
    parent: 'Administrative and Support Services',
  },
  {
    name: 'Steam and Air-Conditioning Supply',
    parent: 'Water, Waste, Steam, and Air Conditioning Services',
  },
  {
    name: 'Strategic Management Services',
    parent: 'Business Consulting and Services',
  },
  {
    name: 'Subdivision of Land',
    parent: 'Civil Engineering',
  },
  {
    name: 'Sugar and Confectionery Product Manufacturing',
    parent: 'Food and Beverage Manufacturing',
  },
  {
    name: 'Surveying and Mapping Services',
    parent: 'Engineering Services',
  },
  {
    name: 'Taxi and Limousine Services',
    parent: 'Ground Passenger Transportation',
  },
  {
    name: 'Technical and Vocational Training',
    parent: 'Education',
  },
  {
    name: 'Technology, Information and Internet',
    parent: 'Technology, Information and Media',
  },
  {
    name: 'Technology, Information and Media',
    parent: null,
  },
  {
    name: 'Telecommunications',
    parent: 'Media and Telecommunications',
  },
  {
    name: 'Telecommunications Carriers',
    parent: 'Telecommunications',
  },
  {
    name: 'Telephone Call Centers',
    parent: 'Administrative and Support Services',
  },
  {
    name: 'Temporary Help Services',
    parent: 'Staffing and Recruiting',
  },
  {
    name: 'Textile Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Theater Companies',
    parent: 'Performing Arts and Spectator Sports',
  },
  {
    name: 'Think Tanks',
    parent: 'Research Services',
  },
  {
    name: 'Tobacco Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Translation and Localization',
    parent: 'Administrative and Support Services',
  },
  {
    name: 'Transportation Equipment Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Transportation Programs',
    parent: 'Economic Programs',
  },
  {
    name: 'Transportation, Logistics, Supply Chain and Storage',
    parent: null,
  },
  {
    name: 'Travel Arrangements',
    parent: 'Administrative and Support Services',
  },
  {
    name: 'Truck Transportation',
    parent: 'Transportation, Logistics, Supply Chain and Storage',
  },
  {
    name: 'Trusts and Estates',
    parent: 'Funds and Trusts',
  },
  {
    name: 'Turned Products and Fastener Manufacturing',
    parent: 'Fabricated Metal Products',
  },
  {
    name: 'Urban Transit Services',
    parent: 'Ground Passenger Transportation',
  },
  {
    name: 'Utilities',
    parent: null,
  },
  {
    name: 'Utilities Administration',
    parent: 'Economic Programs',
  },
  {
    name: 'Utility System Construction',
    parent: 'Civil Engineering',
  },
  {
    name: 'Vehicle Repair and Maintenance',
    parent: 'Repair and Maintenance',
  },
  {
    name: 'Venture Capital and Private Equity Principals',
    parent: 'Capital Markets',
  },
  {
    name: 'Veterinary Services',
    parent: 'Professional Services',
  },
  {
    name: 'Vocational Rehabilitation Services',
    parent: 'Individual and Family Services',
  },
  {
    name: 'Warehousing and Storage',
    parent: 'Transportation, Logistics, Supply Chain and Storage',
  },
  {
    name: 'Waste Collection',
    parent: 'Water, Waste, Steam, and Air Conditioning Services',
  },
  {
    name: 'Waste Treatment and Disposal',
    parent: 'Water, Waste, Steam, and Air Conditioning Services',
  },
  {
    name: 'Water Supply and Irrigation Systems',
    parent: 'Water, Waste, Steam, and Air Conditioning Services',
  },
  {
    name: 'Water, Waste, Steam, and Air Conditioning Services',
    parent: 'Utilities',
  },
  {
    name: 'Wellness and Fitness Services',
    parent: 'Recreational Facilities',
  },
  {
    name: 'Wholesale',
    parent: null,
  },
  {
    name: 'Wholesale Alcoholic Beverages',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Apparel and Sewing Supplies',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Appliances, Electrical, and Electronics',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Building Materials',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Chemical and Allied Products',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Computer Equipment',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Drugs and Sundries',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Food and Beverage',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Footwear',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Furniture and Home Furnishings',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Hardware, Plumbing, Heating Equipment',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Import and Export',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Luxury Goods and Jewelry',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Machinery',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Metals and Minerals',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Motor Vehicles and Parts',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Paper Products',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Petroleum and Petroleum Products',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Photography Equipment and Supplies',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Raw Farm Products',
    parent: 'Wholesale',
  },
  {
    name: 'Wholesale Recyclable Materials',
    parent: 'Wholesale',
  },
  {
    name: 'Wind Electric Power Generation',
    parent: 'Renewable Energy Power Generation',
  },
  {
    name: 'Wineries',
    parent: 'Food and Beverage Manufacturing',
  },
  {
    name: 'Wireless Services',
    parent: 'Telecommunications',
  },
  {
    name: "Women's Handbag Manufacturing",
    parent: 'Leather Product Manufacturing',
  },
  {
    name: 'Wood Product Manufacturing',
    parent: 'Manufacturing',
  },
  {
    name: 'Writing and Editing',
    parent: 'Administrative and Support Services',
  },
  {
    name: 'Zoos and Botanical Gardens',
    parent: 'Museums, Historical Sites, and Zoos',
  },
] as const;

export const SENIORITIES: readonly string[] = [
  'In Training',
  'Entry Level',
  'Senior',
  'Strategic',
  'Entry Level Manager',
  'Experienced Manager',
  'Director',
  'Vice President',
  'CXO',
  'Owner / Partner',
] as const;

export const FUNCTIONS: readonly string[] = [
  'Accounting',
  'Administrative',
  'Arts and Design',
  'Business Development',
  'Community and Social Services',
  'Consulting',
  'Customer Success and Support',
  'Education',
  'Engineering',
  'Entrepreneurship',
  'Finance',
  'Healthcare Services',
  'Human Resources',
  'Information Technology',
  'Legal',
  'Marketing',
  'Media and Communication',
  'Military and Protective Services',
  'Operations',
  'Product Management',
  'Program and Project Management',
  'Purchasing',
  'Quality Assurance',
  'Real Estate',
  'Research',
  'Sales',
] as const;

export const COMPANY_TYPES: readonly string[] = [
  'Educational',
  'Government Agency',
  'Non Profit',
  'Partnership',
  'Privately Held',
  'Public Company',
  'Self Employed',
  'Self Owned',
] as const;

export const HEADCOUNTS: readonly string[] = [
  '1-10',
  '11-50',
  '51-200',
  '201-500',
  '501-1000',
  '1001-5000',
  '5001-10000',
  '10 000+',
] as const;

export const FOLLOWER_RANGES: readonly string[] = ['1-50', '51-100', '101-1000', '1001-5000', '5001+'] as const;
